# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ef92dd2
_src_path: ./
accountname: quickplates
description: Helm charts example ⛵
docs: true
docsurl: https://quickplates.github.io/helm-example
projectname: helm-example
reponame: helm-example
repourl: https://github.com/quickplates/helm-example
